/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ngavax.java-application-conventions")
}


repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("org.json:json:+")
    implementation("com.google.code.gson:gson:+")
}

application {
    // Define the main class for the application.
    mainClass.set("ngavax.app.App")
}
