/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ngavax.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
}

application {
    // Define the main class for the application.
    mainClass.set("ngavax.app.App")
}
