/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ngavax.app;

import static ngavax.app.MessageUtils.*;

public class App {
    public static void main(String[] args) {
        System.out.println(getMessage());
        System.out.println(getOtherMessage());
    }
}
