/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ngavax.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello World!";
    }
    public static String getOtherMessage() {
        return "Hello Other World!";
    }
}
